name: Release
on:
  push:
    tags:
      - '*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@master
        with: 
          python-version: '3.x'
      - run:  python ./.github/scripts/make_db.py
      - name: Create Archive Release
        uses: thedoctor0/zip-release@master
        with:
          filename: 'module.zip'
          exclusions: '*.git*'
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'module.json, module.zip'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Foundry Manifest Update
        id: foundry-manifest-update
        uses: foundryvtt-dcc/foundry-manifest-update-action@main
        with:
          actionToken: ${{ secrets.GITHUB_TOKEN }}
          manifestFileName: 'module.json'
