name: Release
on:
  push:
    branches:
      - 'main'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Modules
        run: yarn
      - name: Run ESLint
        run: eslint . --ext .js,.jsx,.ts,.tsx
      - uses: actions/setup-python@master
        with:
          python-version: '3.x'
      - run: python ./.github/scripts/make_db.py
      - name: Bump Version
        id: bump_version
        run: python ./.github/scripts/bump_version.py
      - name: Create Archive Release
        uses: thedoctor0/zip-release@master
        with:
          filename: 'module.zip'
          exclusions: '*.git*'
      - name: Automatic Release Upload
        id: automatic_release
        uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: ${{ steps.bump_version.outputs.version }}
          prerelease: false
          title: ${{ steps.bump_version.outputs.version }}
          files: |
            module.json
            module.zip

